### ISSUE TITLE
What are the keys for?

### ISSUE THREAD

**Issue by KeenVox** [slipperyseal/monty#1]
Hi, 
I hope I'm not to stupid to read properly, but what do the keys do?

**Comment by slipperyseal** [comment]
There is a simple memu system for editing voice properties (values in the range 0 to F).

```
Knob knobs[] = {
    {'A', &monty.synth.instrument.attackDecay, true },
    {'D', &monty.synth.instrument.attackDecay, false },
    {'S', &monty.synth.instrument.sustainRelease, true },
    {'R', &monty.synth.instrument.sustainRelease, false },
    {'H', &monty.synth.instrument.sineAmplitude, false },
    {'W', &monty.synth.instrument.sineWidth, false },
};
```

Press center button.
Letter flashes.
Move left and right through letters.
Press center again to edit value.
Edit with left and right.
Center to return to letters.

Also, hold the centre button on boot to start playing the Monty On The Run chip tune.

This is one of the last features I added so its fairly redimentary at the moment.

Iv been meaning to add this to the README, ill add something quickly now.
